apiVersion: apps/v1
kind: Deployment
metadata:
  name: plone
  labels:
    app: plone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plone
  template:
    metadata:
      labels:
        app: plone
    spec:
      containers:
      - name: zeo
        image: zopyx/plone-zeo
        ports:
        - containerPort: 20100
      - name: client
        image: zopyx/plone-client
        ports:
        - containerPort: 8080
